
package scilatex.View.Components;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JPanel;
import static scilatex.Data.Constants.Constants.BORDER_COLOR;
import static scilatex.Data.Constants.Constants.COLOR_TEXT;

// Clase que permite visualizar un error en pantalla
public class Notification extends javax.swing.JPanel {

    // Componentes graficos
    private JPanel parent;      // Panel en el cual mostrar el mensaje

    // Iniciar panel que muestra el error
    public Notification(JPanel parent, String title, String content) {
        initComponents();
        this.parent = parent;

        // ASignar texto
        jLabel15.setText(title);
        jLabel16.setText(content);

    }

    // Visualizar error en pantalla
    public void show() {

        Toolkit.getDefaultToolkit().beep();
        parent.add(this).setBounds(parent.getWidth() / 2 - this.getPreferredSize().width / 2, 5,  this.getPreferredSize().width, this.getPreferredSize().height);
        parent.updateUI();

        new Thread("Nombre hilo") {

            @Override
            public void run() {
                
                for (int i = 255; i >= 0; i--) {

                    jLabel15.setForeground(new Color(jLabel15.getForeground().getRed(), jLabel15.getForeground().getGreen(), jLabel15.getForeground().getBlue(), i));
                    jLabel16.setForeground(new Color(jLabel16.getForeground().getRed(), jLabel16.getForeground().getGreen(), jLabel16.getForeground().getBlue(), i));
                    setBorder(javax.swing.BorderFactory.createLineBorder(new Color(BORDER_COLOR.getRed(), BORDER_COLOR.getGreen(), BORDER_COLOR.getBlue(), i), 2));

                    try {
                        Thread.sleep(17);
                    } catch (InterruptedException ex) {
                    }

                }
                
                remove();

            }

        }.start();
        
    }

    // Remover panel de error en pantalla
    public void remove(){
        parent.remove(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 245, 251));
        setBorder(javax.swing.BorderFactory.createLineBorder(BORDER_COLOR, 2));
        setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel15.setForeground(COLOR_TEXT);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Error");

        jLabel16.setFont(new java.awt.Font("Constantia", 0, 14)); // NOI18N
        jLabel16.setForeground(java.awt.Color.red);
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    // End of variables declaration//GEN-END:variables
}
